### ISSUE TITLE
[Question] Is this library plataform independant? (linux/windows)

### ISSUE THREAD

**Issue by mercuriete** [ebts/jet#1]
It seems you are using jni to some functions.

https://github.com/ebts/jet/blob/master/JETExample/nbis_jni.dll

This library is full java or there are some native code?

Please if dll is not needed delete it from the repository because it creates confusion.

PS: Your work is awesome. I really like it. Thank you very much. :smile: :+1:

**Comment by wvucam71** [comment]
Thanks @mercuriete.  This file was hanging out from a test application we had that was utilized before we found the JNBIS implementation for WSQ compression.  The JET library itself is in fact platform independent.

**Comment by mercuriete** [comment]
thank you very much!
:+1:  :smile:
