### ISSUE TITLE
NullPointerException loading properties file in executable JAR

### ISSUE THREAD

**Issue by ericcarte** [ebts/jet#12]
**Error text**: java.lang.NullPointerException: null ... at org.mitre.jet.ebts.EbtsUtils.loadPropertiesFile (EbtsUtils.java:100) ...

**Environment**: Eclipse IDE for Java Developers version 2018-12 (4.10.0), Java SE 1.8.0_202-b08, 64-bit Windows 10.

No issues when running from Eclipse; only after exporting to Executable JAR and running from command line.

I have verified that the 'TagMap.properties' file is in the '/resources' folder of the JAR.

**Comment by ericcarte** [comment]
After researching this issue more, I believe it to be an "Eclipse" issue rather than a "Jet" issue.  Numerous people on sites such as 'stackoverflow' have reported problems with resource access when using Eclipse to create a JAR.

By modifying PROP_FILE_DEFAULT in EbtsUtils.java to be '/resources/TagMap.properties' which reflects the packaging of resources in the JARs that Eclipse creates, I was able to eliminate the problem.

**Comment by adamday2** [comment]
Thanks for bringing up this issue. Next time we do an update, I'll see if there is an alternate method for referencing the resources that might help eliminate this problem.
