### ISSUE TITLE
EBTSParser throws an exception with empty 10.999 fields

### ISSUE THREAD

**Issue by jej2003** [ebts/jet#3]
I've encountered several EFTs that for whatever reason do not have data in the 10.999 fields.  From a quick glance at the code it appears that this could be a 1 line update to EBTSParser to populate the field with an empty byte[] in this case by updating line 305 to not check if the readLength is 0

`if (record.getLength() != -1 && bb.remaining() >= readLength) {`

Is there anyway this could be supported?

**Comment by adamday2** [comment]
I'll put a patch in for this shortly. Should be a relatively easy fix.

**Comment by jej2003** [comment]
awesome, thanks!  The following attachment should be useful for testing.  I based it on an existing EFT in the test folder
[empty_image.eft.zip](https://github.com/ebts/jet/files/1679379/empty_image.eft.zip)
