### ISSUE TITLE
The parsing of type 7 records assumes type 4 fields are present

### ISSUE THREAD

**Issue by jej2003** [ebts/jet#4]
when parsing type 7 records the current implementation assumes that a number of fields associated with type 4 records (IMP, FGP, ISR, HLL, VLL, CGA) are present but per the specification (http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.500-290e3.pdf) there is no guarantee that any of these will be set.  This causes the parsing of some efts to fail when HLL and VLL are read incorrectly and cause a read beyond the buffers size.  

Ideally, the parsing of this field would only pull the specification defined fields (header, IDC and binary value).

**Comment by adamday2** [comment]
Thanks for point out this issue. 
You make a good point - I'll look into adding a flag that allows you to select parsing options to treat Type 7 as Type 4 or just header, IDC, binary. I need to keep the legacy behavior to not break backwards compatibility and because some organizations put Type 4 data in there.

**Comment by jej2003** [comment]
That would be great, having the option would suite my needs particularly well.  We unfortunately don't have insight into these EFTs or their contents so at this point handling it as binary is our only option.  Would have been nice if there was some way to determine what information is and is not present but I don't think that's possible.  Regardless having the option to parse it as header, IDC and binary would scratch my particular itch.

**Comment by jej2003** [comment]
Has there been any movement on this?  I'm currently keeping a fork of the code base to work around this but I'd prefer to work off this repository.

**Comment by adamday2** [comment]
No movement on this yet, but planning a fix shortly. Apologies for the delay.

**Comment by jej2003** [comment]
I opened https://github.com/ebts/jet/pull/8 to address this.  I think it satisfies your requirement that your existing customer base still work as is without requiring any huge changes.  let me know your thoughts

**Comment by adamday2** [comment]
@jej2003 I ended up making some changes to what you had proposed to keep the separation a little cleaner and to continue to handle an odd use-case.

I realize the parse(chain of parameters) is getting a bit absurd, so I'll probably end up switching these methods away from static and using the builder pattern to create re-usable EbtsParsers, so you'll be able to do something like this in the new future:

`EbtsParser parser = EbtsParser.setType7Handling(NIST).setParseType(Full).build();`

Let me know if the changes meet your needs.

**Comment by jej2003** [comment]
Will give this a run today.  We actually have several EFTs that require both types of handling so the big concern is that I don't have a sufficient way to know up front how to treat each record.  This may still work but I think it will require me to attempt to read one way and fallback to the other.  Will need to investigate further today

**Comment by adamday2** [comment]
Sounds good. Let me know how it works for you. I'm happy to adjust and try to incorporate some automatic handling. The only way I can think off of the top of my head is to attempt to parse as Type4, validate the field values, and if they don't make sense, fall back to just parse as a header w/ [4,1].

**Comment by jej2003** [comment]
This was exactly my thought.  We actually came across a situation today where not every type 7 record was written as type 4 so in order to handle this we'd need an automatic approach.  Would it be possible to add a 3rd value where it's something like "best try" and acts as you say?

**Comment by adamday2** [comment]
I'm completely supportive of adding the option and would probably set it as the default handling.

I can probably hack something together early next week based on the expected values for the type4 fields and if its not in range, fallback to type7. It'll probably be next week until I get to it, but if you are able to do a pull request, I'd be happy to merge it in.

**Comment by jej2003** [comment]
I'm pretty sure my week is slammed but I'll see if someone else can help out.  The original pull request I had put together sort of did this so shouldn't be all that difficult bring it over.
