### ISSUE TITLE
Added flexible Type7 handling

### ISSUE THREAD

**Issue by adamday2** [ebts/jet#9]
Support the ability to attempt to parse a Type7 record as Type4, and if field validation fails on 7.03-7.09, fallback to processing as specified by NIST standard (7.01, 7.02, image_data)

**Comment by mywill** [comment]
@adamday2 I opened a pull request to attempt to do this https://github.com/ebts/jet/pull/10

**Comment by adamday2** [comment]
Closed in https://github.com/ebts/jet/pull/13
